# Generated by Django 4.0 on 2021-12-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0002_bloguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='username',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
