# Generated by Django 4.0 on 2021-12-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedpost',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
