# Generated by Django 4.0 on 2021-12-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivity', '0002_alter_likedpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedpost',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
