# Generated by Django 4.0 on 2021-12-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0003_bloguser_username'),
        ('useractivity', '0004_useractivity_remove_likedpost_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloguser.bloguser'),
        ),
    ]
