# Generated by Django 4.0 on 2021-12-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0002_bloguser'),
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bloguser.bloguser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
