# Generated by Django 4.0 on 2021-12-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogpost_author_alter_blogpost_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=1, max_length=1020),
            preserve_default=False,
        ),
    ]
