# Generated by Django 4.0 on 2021-12-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-last_update']},
        ),
    ]
